FROM python:3.11
EXPOSE 8001

RUN adduser --disabled-password --gecos "" rest_server
USER rest_server
WORKDIR /home/rest_server
ENV PATH="/home/rest_server/.local/bin:${PATH}"
COPY --chown=rest_server:rest_server requirements.txt requirements.txt
COPY --chown=rest_server:rest_server requirements-torch.txt requirements-torch.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-torch.txt
COPY --chown=rest_server:rest_server . .

ENTRYPOINT ["python", "FastAPI.py"]


